Uplift GitHub Action upload-artifact version.
The CI jobs fail with the error:

> Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

Moving to version 4 to fix the error.